export interface Vehicle {
    name: string,
    cargo_capacity: string,
    consumables: string,
    cost_in_credits: string,
    created: string,
    edited: string,
    crew: string,
    manufacturer: string,
    max_atmosphering_speed: string,
    model: string,
    passengers: string,
    pilots: string[],
    films: string[],
    url: string,
    vehicle_class: string,
}